#!/bin/bash

mv "test/Assembler/2003-11-11-ImplicitRename.ll" "test/Assembler/2003-11-11-ImplicitRename.ll.x"
mv "test/Assembler/2004-03-30-UnclosedFunctionCrash.ll" "test/Assembler/2004-03-30-UnclosedFunctionCrash.ll.x"
mv "test/Assembler/2003-11-24-SymbolTableCrash.ll" "test/Assembler/2003-11-24-SymbolTableCrash.ll.x"
mv "test/Assembler/2004-11-28-InvalidTypeCrash.ll" "test/Assembler/2004-11-28-InvalidTypeCrash.ll.x"
mv "test/Assembler/2006-09-28-CrashOnInvalid.ll" "test/Assembler/2006-09-28-CrashOnInvalid.ll.x"
mv "test/Assembler/2007-01-02-Undefined-Arg-Type.ll" "test/Assembler/2007-01-02-Undefined-Arg-Type.ll.x"
mv "test/Assembler/2007-08-06-AliasInvalid.ll" "test/Assembler/2007-08-06-AliasInvalid.ll.x"
mv "test/Assembler/2007-11-26-AttributeOverload.ll" "test/Assembler/2007-11-26-AttributeOverload.ll.x"
mv "test/Assembler/2008-02-18-IntPointerCrash.ll" "test/Assembler/2008-02-18-IntPointerCrash.ll.x"
mv "test/Assembler/alias-redefinition.ll" "test/Assembler/alias-redefinition.ll.x"
mv "test/Assembler/align-inst-load.ll" "test/Assembler/align-inst-load.ll.x"
mv "test/Assembler/align-inst-store.ll" "test/Assembler/align-inst-store.ll.x"
mv "test/Assembler/alloca-addrspace-parse-error-0.ll" "test/Assembler/alloca-addrspace-parse-error-0.ll.x"
mv "test/Assembler/alloca-addrspace-parse-error-1.ll" "test/Assembler/alloca-addrspace-parse-error-1.ll.x"
mv "test/Assembler/alloca-invalid-type.ll" "test/Assembler/alloca-invalid-type.ll.x"
mv "test/Assembler/asm-path-writer.ll" "test/Assembler/asm-path-writer.ll.x"
mv "test/Assembler/call-invalid-1.ll" "test/Assembler/call-invalid-1.ll.x"
